openapi: 3.0.3
info:
  title: 'Site Developer Api Documentation for Serveronet'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://site_id.snet.localhost:15080'
tags:
  -
    name: 'Helper APIs'
    description: ''
  -
    name: 'Records and Resources'
    description: ''
  -
    name: Endpoints
    description: ''
paths:
  /site_api/v1/csrf-cookie:
    get:
      summary: 'CSRF cookie'
      operationId: cSRFCookie
      description: 'Return an empty response simply to trigger the storage of the CSRF cookie in the browser.'
      parameters: []
      responses:
        204:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'No Content'
      tags:
        - 'Helper APIs'
  /site_api/v1/site_state:
    post:
      summary: 'Site State'
      operationId: siteState
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"site_id\": \"abc\", ...\n      }\n    ]\n}"
      tags:
        - 'Helper APIs'
      security: []
  /site_api/v1/is_authenticated:
    post:
      summary: 'Is Authenticated'
      operationId: isAuthenticated
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    is_authenticated: true
                    visitor_id: 1abc
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      is_authenticated:
                        type: boolean
                        example: true
                      visitor_id:
                        type: string
                        example: 1abc
      tags:
        - 'Helper APIs'
  /site_api/v1/client_config:
    post:
      summary: 'Client Config'
      operationId: clientConfig
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"post_max_size\": \"8 MiB\",...\n      }\n    ]\n}"
      tags:
        - 'Helper APIs'
      security: []
  /site_api/v1/mime_types_mapping:
    post:
      summary: 'Mime Type Mapping'
      operationId: mimeTypeMapping
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: '{"success":true,"data":{"1km":"application\/vnd.1000minds.decision-model+xml",...'
      tags:
        - 'Helper APIs'
      security: []
  /site_api/v1/get_visitor_state:
    post:
      summary: 'Visitor State'
      operationId: visitorState
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"visitor_id\": \"131NUHD9mqeCuNGrchfvFp4ZWeBWRNk6hF\",\n          \"is_site_admin\": false,\n      }\n    ]\n}"
      tags:
        - 'Helper APIs'
  /site_api/v1/query_endpoint:
    post:
      summary: 'Site API Query Endpoint'
      operationId: siteAPIQueryEndpoint
      description: 'Endpoint to query local or peer database'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    -
                      body: 'Post body'
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    example:
                      -
                        body: 'Post body'
                    items:
                      type: object
                      properties:
                        body:
                          type: string
                          example: 'Post body'
      tags:
        - 'Records and Resources'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query_parameters:
                  type: json
                  description: ''
                  example: 'Json body of query parameters - {"table":"posts","where":[["title","!=","excluded_title"]]}'
              required:
                - query_parameters
  /site_api/v1/visitor_files:
    post:
      summary: 'Get Visitor Files'
      operationId: getVisitorFiles
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  data:
                    -
                      entity_id: 2026...
                      original_file_name: ...
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    example:
                      -
                        entity_id: 2026...
                        original_file_name: ...
                    items:
                      type: object
                      properties:
                        entity_id:
                          type: string
                          example: 2026...
                        original_file_name:
                          type: string
                          example: ...
      tags:
        - 'Records and Resources'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                query_parameters:
                  type: string
                  description: ''
                  example: '{"visitor_id":"hwy4phcbfbigqgr5duodyntqcz34ypr2bdwx6d3oa36rsuvujt7a"}'
  '/visitor_file/{visitor_entity_id}':
    get:
      summary: 'Serve Visitor File'
      operationId: serveVisitorFile
      description: 'Get contents of Visitor Resource (File) by specifing id of previously uploaded file'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example: {  }
                properties: {  }
      tags:
        - 'Records and Resources'
      security: []
    parameters:
      -
        in: path
        name: visitor_entity_id
        description: 'Optional parameter. Id of a visitor resource.'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 20261216121630346240_hwy4...
  /site_api/v1/visitor_record_create:
    post:
      summary: 'Visitor Record Create'
      operationId: visitorRecordCreate
      description: "Receives a json body of a record to be created (in _sn_record_json parameters)\nJson requires target table (_sn_table) and site's database fields"
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"entity_id\": \"2026...\",\n      }\n    ]\n}"
      tags:
        - 'Records and Resources'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _sn_record_json:
                  type: string
                  description: ''
                  example: '{"title":"My title", "_sn_table":"posts"}'
              required:
                - _sn_record_json
  /site_api/v1/visitor_record_update:
    post:
      summary: 'Visitor Record Update'
      operationId: visitorRecordUpdate
      description: "Receives a json body of a record to be updated (in _sn_record_json parameters)\nJson requires target table (_sn_table), entity id to be updated (_sn_entity_id)\nand site's database fields"
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"entity_id\": \"2026...\",\n      }\n    ]\n}"
      tags:
        - 'Records and Resources'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                _sn_record_json:
                  type: string
                  description: ''
                  example: '{"title":"My title", "_sn_table":"posts"}'
              required:
                - _sn_record_json
  /site_api/v1/visitor_file_upload:
    post:
      summary: 'Visitor File Upload'
      operationId: visitorFileUpload
      description: 'Upload a file as form data'
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n      \"success\":true,\"data\": {\"id\":\"new_id\"},..."
      tags:
        - 'Records and Resources'
      requestBody:
        required: true
        content:
          undefined:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: ''
                  example: formData
              required:
                - data
  /site_api/v1/visitor_file_delete:
    post:
      summary: 'Visitor File Delete'
      operationId: visitorFileDelete
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  metadata: 2026...
                properties:
                  success:
                    type: boolean
                    example: true
                  metadata:
                    type: string
                    example: 2026...
      tags:
        - 'Records and Resources'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                _sn_entity_id:
                  type: '{string}'
                  description: ''
                  example: '"2026..."'
  /site_api/v1/check_can_post_to_table:
    post:
      summary: 'Check Can Post to Table'
      operationId: checkCanPostToTable
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"can_post_to_table\": \"true\",\n      }\n    ]\n}"
      tags:
        - 'Records and Resources'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                table:
                  type: '{string}'
                  description: ''
                  example: posts
  /site_api/v1/check_can_upload:
    post:
      summary: 'Check Can Upload'
      operationId: checkCanUpload
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"data\": [\n      {\n          \"can_upload_files\": \"true\",\n      }\n    ]\n}"
      tags:
        - 'Records and Resources'
  /site_api/v1/sse_stream:
    get:
      summary: ''
      operationId: getSite_apiV1Sse_stream
      description: ''
      parameters: []
      responses:
        400:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"robots\" content=\"noindex,nofollow,noarchive\" />\n    <title>An Error Occurred: Bad Request</title>\n    <link rel=\"icon\" href=\"data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>❌</text></svg>\" />\n    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, sans-serif; margin: 0; }\n.container { margin: 30px; max-width: 600px; }\nh1 { color: #dc3545; font-size: 24px; }\nh2 { font-size: 18px; }</style>\n</head>\n<body>\n<div class=\"container\">\n    <h1>Oops! An Error Occurred</h1>\n    <h2>The server returned a \"400 Bad Request\".</h2>\n\n    <p>\n        Something is broken. Please let us know what you were doing when this error occurred.\n        We will fix it as soon as possible. Sorry for any inconvenience caused.\n    </p>\n</div>\n</body>\n</html>"
      tags:
        - Endpoints
      security: []
